# Copyright (c) Meta Platforms, Inc. and affiliates.
# All rights reserved.
# This source code is licensed under the BSD-style license found in the
# LICENSE file in the root directory of this source tree.

# This workflow is used for MSLK CUDA CI as well as nightly builds of MSLK CUDA
# against PyTorch-CUDA Nightly.
name: MSLK CUDA CI

on:
  # Disabled automatic Linux CUDA CI triggers for the Windows-focused MSLK-WIN fork.
  workflow_dispatch:
    inputs:
      pytorch-channel-version:
        description: Package Channel + Version to Use for PyTorch Installation, in `<channel>[/<version>]` Format
        type: string
        required: false
        default: ""
      publish-to-pypi:
        description: Publish Artifact to PyPI
        type: boolean
        required: false
        default: false

concurrency:
  # Cancel previous runs in the PR if a new commit is pushed
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  generate-build-matrix:
    if: ${{ github.repository_owner == 'meta-pytorch' }}
    uses: ./.github/workflows/_mslk_generate_ci_matrix.yml
    with:
      repo-owner: ${{ github.repository_owner }}
      repo-ref: ${{ (github.event_name == 'schedule' && 'nightly') || github.ref }}
      targets: default
      variant: cuda
      jobtype: build

  build:
    needs: generate-build-matrix
    uses: ./.github/workflows/_mslk_cuda_build.yml
    with:
      matrix: ${{ needs.generate-build-matrix.outputs.matrix }}
      repo-ref: ${{ (github.event_name == 'schedule' && 'nightly') || github.ref }}
      pytorch-channel-version: ${{ (github.event_name == 'workflow_dispatch' && github.event.inputs.pytorch-channel-version) || 'nightly' }}

  generate-test-matrix:
    needs: build
    uses: ./.github/workflows/_mslk_generate_ci_matrix.yml
    with:
      repo-owner: ${{ github.repository_owner }}
      repo-ref: ${{ (github.event_name == 'schedule' && 'nightly') || github.ref }}
      targets: default
      variant: cuda
      jobtype: test

  test:
    needs: generate-test-matrix
    uses: ./.github/workflows/_mslk_cuda_test.yml
    with:
      matrix: ${{ needs.generate-test-matrix.outputs.matrix }}
      repo-ref: ${{ (github.event_name == 'schedule' && 'nightly') || github.ref }}
      pytorch-channel-version: ${{ (github.event_name == 'workflow_dispatch' && github.event.inputs.pytorch-channel-version) || 'nightly' }}
      publish-to-pypi: ${{ (github.event_name == 'schedule') || (github.event_name == 'workflow_dispatch' && github.event.inputs.publish-to-pypi == 'true') }}
      cuda-version-publish: 12.8.1
    secrets:
      PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
